if(isServer) then
{
[-2, {tongue globalChat _this}, "Hey, dont shoot!"] call CBA_fnc_globalExecute;
sleep 5;
[-2, {leader player sideChat _this}, "Don't move! Stay calm. I wanna see your hands."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "I don't wanna hurt you, I'm unarmed! I'm friend of you."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {leader player sideChat _this}, "Shut up. If you know something interesting, youi'll live. Do you know where is our friend?"] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "No, I said, i have meds for you, i have ammunition, you can grab it, just let me go."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {leader player sideChat _this}, "What? You allow me grab meds? I can grab everything here, even information, hidden in your brain. Trust me, I can make you tell me everything."] call CBA_fnc_globalExecute;
sleep 8;
[-2, {tongue globalChat _this}, "I can't, they'll kill me..."] call CBA_fnc_globalExecute;
sleep 3;
[-2, {leader player sideChat _this}, "Good way, or bad way?"] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "...and all my family, I can't say..."] call CBA_fnc_globalExecute;
sleep 3;
[-2, {leader player sideChat _this}, "Good way, or bad way?"] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "Okay, okay! When you pilot fell from skies, he was unconscious."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "Soldiers bring him to me and I stabilised him."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {leader player sideChat _this}, "Is he alive?"] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "Should be, but he is heavy wounded, seems he broke his spine. Soldiers grab him from me about ten minutes ago."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {leader player sideChat _this}, "Fucking great. Where is he? Tell me and you can go to your family."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "I think, he might be on one of three places - mini bases of militia. First in hangar on the south, second is abandoned shop, where we store food and water, and third is old warehouse closer to city center. I can mark them on a map."] call CBA_fnc_globalExecute;
sleep 8;
[-2, {leader player sideChat _this}, "Good."] call CBA_fnc_globalExecute;
sleep 5;
[-2, {tongue globalChat _this}, "But your friend can't walk, you can't escape with him."] call CBA_fnc_globalExecute;
};
