if(isServer) then
{
	_point = _this select 0;
	_pgun = _this select 1;
	_pgun2 = _this select 2;
	_pgun3 = _this select 3;
	_pgun4 = _this select 4;
	_dgun = _this select 5;
	_dgun2 = _this select 6;
	_dgun3 = _this select 7;
	_dgun4 = _this select 8;
	_myGroup = createGroup east;
	_tempSoldier = _myGroup createUnit ["TK_INS_Soldier_TL_EP1",getMarkerPos _point,[],0.8,"Sergeant"];
	_tempSoldier2 = _myGroup createUnit ["TK_INS_Soldier_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier3 = _myGroup createUnit ["TK_INS_Soldier_MG_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier4 = _myGroup createUnit ["TK_INS_Soldier_AR_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier5 = _myGroup createUnit ["TK_INS_Bonesetter_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier6 = _myGroup createUnit ["TK_INS_Soldier_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier7 = _myGroup createUnit ["TK_INS_Soldier_EP1",getMarkerPos _point,[],0.6,"Private"];
	_gun = "DSHkM_Mini_TriPod_TK_INS_EP1" createVehicle (getMarkerPos _pgun);
	_gun2 = "DSHkM_Mini_TriPod_TK_INS_EP1" createVehicle (getMarkerPos _pgun2);
	_gun3 = "DSHkM_Mini_TriPod_TK_INS_EP1" createVehicle (getMarkerPos _pgun3);
	_gun4 = "DSHkM_Mini_TriPod_TK_INS_EP1" createVehicle (getMarkerPos _pgun4);
	_gun setDir _dgun;
	_gun2 setDir _dgun2;
	_gun3 setDir _dgun3;
	_gun4 setDir _dgun4;
	_tempSoldier8 = _myGroup createUnit ["TK_INS_Soldier_3_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier9 = _myGroup createUnit ["TK_INS_Soldier_3_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier10 = _myGroup createUnit ["TK_INS_Soldier_3_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier11 = _myGroup createUnit ["TK_INS_Soldier_3_EP1",getMarkerPos _point,[],0.6,"Private"];
	_tempSoldier8 moveInGunner _gun;
	_tempSoldier9 moveInGunner _gun2;
	_tempSoldier10 moveInGunner _gun3;
	_tempSoldier11 moveInGunner _gun4;
	wp = _myGroup addwaypoint [getMarkerPos _point,5];
	wp setWaypointType "GUARD";
	wp setWaypointBehaviour "SAFE";
	wp setWaypointCombatMode "RED";
};
