_box = _this select 0;
_class = typeOf player;
_gl = ["ACE_USMC_Soldier_TL_D","ACE_USMC_Soldier_D"];
_ar = ["ACE_USMC_Soldier_AR_D"];
_mg = ["ACE_USMC_Soldier_MG_D"];
_dm = ["ACE_USMC_SoldierM_Marksman_D"];
_at = ["ACE_USMC_Soldier_AT_D"];
_tl = ["ACE_USMC_Soldier_TL_D"];
_noat = ["ACE_USMC_Soldier_Medic_D","ACE_USMC_Soldier_AR_D","ACE_USMC_SoldierM_Marksman_D","ACE_USMC_Soldier_MG_D"];

while {true} do
{
clearMagazineCargo _box;
clearWeaponCargo _box;
_box setammocargo 0;

	_box addweaponcargo ["ACE_ParachutePack",5];
	_box addweaponcargo ["ACE_ParachuteRoundPack",5];
	_box addweaponcargo ["Binocular",5];
	_box addweaponcargo ["Binocular_Vector",5];
	_box addweaponcargo ["ACE_YardAge450",5];
	_box addweaponcargo ["NVGoggles",5];
	_box addweaponcargo ["ACE_Map_Tools",5];
	_box addweaponcargo ["ACE_Earplugs",5];
	_box addweaponcargo ["ACE_WIRECUTTER",5];
	_box addweaponcargo ["ACE_DAGR",5];
	_box addweaponcargo ["ACE_SpottingScope",5];
	_box addweaponcargo ["ACE_Keycuffs",5];
	_box addweaponcargo ["ACE_GlassesGasMask_US",5];
	_box addweaponcargo ["ACE_GlassesLHD_glasses",5];
	_box addweaponcargo ["ace_arty_rangeTable_m224_legacy",5];
	_box addweaponcargo ["ACE_Arty_AimingPost_M1A2_M58",5];
	_box addweaponcargo ["ACE_Arty_AimingPost_M1A2_M59",5];
	_box addweaponcargo ["ItemMap",5];
	_box addweaponcargo ["ItemRadio",5];
	_box addweaponcargo ["ItemWatch",5];
	_box addweaponcargo ["ItemCompass",5];

	_box addweaponcargo ["M16A2",1];
	_box addweaponcargo ["ACE_m16a2_scope",1];
	_box addweaponcargo ["M16A4",1];
	_box addweaponcargo ["ACE_M16A4_Iron",1];
	_box addweaponcargo ["M16A4_ACG",1];
	_box addweaponcargo ["ACE_M4",1];
	_box addweaponcargo ["ACE_M4_Aim",1];
	_box addweaponcargo ["ACE_M4_Eotech",1];
	_box addweaponcargo ["ACE_M4_ACOG",1];
	_box addweaponcargo ["M4A1",1];
	_box addweaponcargo ["M4A1_Aim",1];
	_box addweaponcargo ["M4A1_AIM_SD_camo",1];
	_box addweaponcargo ["M4A3_CCO_EP1",1];
	_box addweaponcargo ["ACE_SOC_M4A1_Aim",1];
	_box addweaponcargo ["ACE_SOC_M4A1_AIM_SD",1];
	_box addweaponcargo ["ACE_SOC_M4A1",1];
	_box addweaponcargo ["ACE_SOC_M4A1_Eotech",1];
	_box addweaponcargo ["ACE_SOC_M4A1_Eotech_4x",1];
	_box addweaponcargo ["ACE_SOC_M4A1_SD_9",1];
	_box addweaponcargo ["ACE_SOC_M4A1_SHORTDOT",1];
	_box addweaponcargo ["ACE_SOC_M4A1_SHORTDOT_SD",1];
	_box addweaponcargo ["ACE_M4A1_ACOG",1];
	_box addweaponcargo ["ACE_M4A1_ACOG_SD",1];
	_box addweaponcargo ["ACE_M4A1_Aim_SD",1];
	_box addweaponcargo ["ACE_M4A1_Eotech",1];
	_box addweaponcargo ["ACE_HK416_D10",1];
	_box addweaponcargo ["ACE_HK416_D10_COMPM3",1];
	_box addweaponcargo ["ACE_HK416_D10_COMPM3_SD",1];
	_box addweaponcargo ["ACE_HK416_D10_AIM",1];
	_box addweaponcargo ["ACE_HK416_D10_SD",1];
	_box addweaponcargo ["ACE_HK416_D14",1];
	_box addweaponcargo ["ACE_HK416_D14_COMPM3",1];
	_box addweaponcargo ["ACE_HK416_D14_SD",1];
	_box addweaponcargo ["ACE_HK416_D14_ACOG_PVS14",1];
	_box addweaponcargo ["ACE_HK417_Shortdot",1];
	_box addweaponcargo ["ACE_HK417_micro",1];
	_box addweaponcargo ["ACE_HK417_Eotech_4x",1];
	_box addweaponcargo ["ACE_G3A3",1];
	_box addweaponcargo ["SCAR_L_STD_HOLO",1];
	_box addweaponcargo ["SCAR_L_CQC",1];
	_box addweaponcargo ["SCAR_L_CQC_Holo",1];
	_box addweaponcargo ["SCAR_L_CQC_CCO_SD",1];
	_box addweaponcargo ["SCAR_L_STD_Mk4CQT",1];
	_box addweaponcargo ["SCAR_H_CQC_CCO_SD",1];
	_box addweaponcargo ["SCAR_H_CQC_CCO",1];
	_box addweaponcargo ["M1014",1];
	_box addweaponcargo ["ACE_M1014_Eotech",1];
	_box addweaponcargo ["ACE_MP5A5",1];
	_box addweaponcargo ["MP5A5",1];
	_box addweaponcargo ["ACE_MP5SD",1];
	_box addweaponcargo ["MP5SD",1];
	_box addweaponcargo ["ACE_MP5A4",1];
	_box addweaponcargo ["ACE_UMP45",1];
	_box addweaponcargo ["ACE_UMP45_SD",1];
	_box addweaponcargo ["ACE_UMP45_AIM",1];
	_box addweaponcargo ["ACE_UMP45_AIM_SD",1];
	_box addweaponcargo ["ACE_KAC_PDW",1];
	_box addweaponcargo ["M8_carbine",1];
	_box addweaponcargo ["M8_compact",1];
	_box addweaponcargo ["m8_compact_pmc",1];
	_box addweaponcargo ["m8_carbine_pmc",1];
	_box addweaponcargo ["m8_holo_sd",1];
	_box addweaponcargo ["M14_EP1",1];
	
if !(_class in _noat) then {	
	_box addweaponcargo ["M136",1];
	_box addweaponcargo ["ACE_M72A2",1];
};
	
	_box addweaponcargo ["ACE_PRC119",1];
	_box addweaponcargo ["ACE_Rucksack_MOLLE_DMARPAT",1];
	_box addweaponcargo ["ACE_Rucksack_MOLLE_DMARPAT_Medic",1];
	_box addweaponcargo ["ACE_Stretcher",1];
	_box addweaponcargo ["ACE_VTAC_RUSH72",1];
	_box addweaponcargo ["ACE_M224TripodProxy",1];
	_box addweaponcargo ["ACE_M224Proxy",1];
	_box addweaponcargo ["ACE_M3TripodProxy",1];
	_box addweaponcargo ["ACE_M2HBProxy",1];
	_box addweaponcargo ["ACE_MK19MOD3Proxy",1];		

	_box addweaponcargo ["Colt1911",1];
	_box addweaponcargo ["M9",1];
	_box addweaponcargo ["M9SD",1];
	_box addweaponcargo ["revolver_EP1",1];
	_box addweaponcargo ["ACE_USP",1];
	_box addweaponcargo ["ACE_USPSD",1];
	_box addweaponcargo ["ACE_L9A1",1];
	_box addweaponcargo ["ACE_MugLite",1];	
	
	_box addmagazinecargo ["ACE_C4_M",50];
	_box addmagazinecargo ["ace_1rnd_cs_m203",50];
	_box addmagazinecargo ["ace_1Rnd_HE_M203",50];
	_box addmagazinecargo ["IR_Strobe_Marker",50];
	_box addmagazinecargo ["ace_m84",50];
	_box addmagazinecargo ["ace_m34",50];
	_box addmagazinecargo ["ACE_M2SLAM_M",50];
	_box addmagazinecargo ["ACE_Rope_M_120",50];
	_box addmagazinecargo ["ACE_Rope_M5",50];
	_box addmagazinecargo ["ACE_Rope_TOW_M_5",50];
	_box addmagazinecargo ["100Rnd_556x45_BetaCMag",50];
	_box addmagazinecargo ["ACE_20Rnd_762x51_B_HK417",50];
	_box addmagazinecargo ["ACE_30Rnd_6x35_B_PDW",50];
	_box addmagazinecargo ["ACE_8Rnd_12Ga_Buck00",50];
	_box addmagazinecargo ["ACE_8Rnd_12Ga_Slug",50];
	_box addmagazinecargo ["ACE_20Rnd_556x45_S_Stanag",50];
	_box addmagazinecargo ["SMAW_HEAA",10];
	_box addmagazinecargo ["SMAW_HEDP",10];
	_box addmagazinecargo ["ACE_SMAW_Spotting",50];
	_box addmagazinecargo ["ACE_Battery_Rangefinder",50];
	_box addmagazinecargo ["10Rnd_127x99_m107",25];
	_box addmagazinecargo ["ACE_20Rnd_762x51_S_M110",50];
	_box addmagazinecargo ["ACE_20Rnd_762x51_SB_M110",50];
	_box addmagazinecargo ["ACE_10Rnd_127x99_Raufoss_m107",50];
	_box addmagazinecargo ["ACE_10Rnd_127x99_T_m107",50];
	_box addmagazinecargo ["ACE_25Rnd_1143x23_B_UMP45",50];
	_box addmagazinecargo ["ACE_25Rnd_1143x23_S_UMP45",50];
	_box addmagazinecargo ["ACE_13Rnd_9x19_L9A1",50];
	_box addmagazinecargo ["ACE_12Rnd_45ACP_USP",50];
	_box addmagazinecargo ["ACE_12Rnd_45ACP_USPSD",50];
	_box addmagazinecargo ["ACE_20Rnd_762x51_B_G3",50];
	_box addmagazinecargo ["ACE_M224HE_CSWDM",10];
	_box addmagazinecargo ["ACE_M224IL_CSWDM",10];
	_box addmagazinecargo ["ACE_M224WP_CSWDM",10];
	_box addmagazinecargo ["ACE_M2_CSWDM",10];
	_box addmagazinecargo ["ACE_MK19_CSWDM",10];
	_box addmagazinecargo ["20Rnd_762x51_DMR",50];
	_box addmagazinecargo ["6Rnd_45ACP",50];
	_box addmagazinecargo ["30Rnd_556x45_Stanag",50];
	_box addmagazinecargo ["5Rnd_762x51_M24",50];
	_box addmagazinecargo ["100Rnd_762x51_M240",50];
	_box addmagazinecargo ["200Rnd_556x45_M249",50];
	_box addmagazinecargo ["ACE_200Rnd_556x45_T_M249",50];
	_box addmagazinecargo ["20Rnd_762x51_B_SCAR",50];
	_box addmagazinecargo ["20rnd_762x51_B_SCAR",50];
	_box addmagazinecargo ["Laserbatteries",50];
	_box addmagazinecargo ["Mine",50];
	_box addmagazinecargo ["PipeBomb",50];
	_box addmagazinecargo ["15Rnd_9x19_M9",50];
	_box addmagazinecargo ["7Rnd_45ACP_1911",50];
	_box addmagazinecargo ["HandGrenade_West",50];
	_box addmagazinecargo ["1Rnd_HE_M203",50];
	_box addmagazinecargo ["1Rnd_Smoke_M203",50];
	_box addmagazinecargo ["SmokeShell",50];
	_box addmagazinecargo ["SmokeShellRed",50];
	_box addmagazinecargo ["SmokeShellGreen",50];
	_box addmagazinecargo ["SmokeShellBlue",50];
	_box addmagazinecargo ["SmokeShellYellow",50];
	_box addmagazinecargo ["SmokeShellOrange",50];
	_box addmagazinecargo ["SmokeShellPurple",50];
	_box addmagazinecargo ["FlareWhite_M203",50];
	_box addmagazinecargo ["FlareYellow_M203",50];
	_box addmagazinecargo ["FlareGreen_M203",50];
	_box addmagazinecargo ["FlareRed_M203",50];
	_box addmagazinecargo ["1Rnd_SmokeRed_M203",50];
	_box addmagazinecargo ["1Rnd_SmokeGreen_M203",50];
	_box addmagazinecargo ["30Rnd_9x19_MP5",50];
	_box addmagazinecargo ["30Rnd_9x19_MP5SD",50];
	_box addmagazinecargo ["20Rnd_556x45_Stanag",50];
	_box addmagazinecargo ["30Rnd_556x45_StanagSD",50];
	
	_box addmagazinecargo ["ACE_Knicklicht_B",5];
	_box addmagazinecargo ["ACE_Knicklicht_G",5];
	_box addmagazinecargo ["ACE_Knicklicht_IR",5];
	_box addmagazinecargo ["ACE_Knicklicht_R",5];
	_box addmagazinecargo ["ACE_Knicklicht_W",5];
	_box addmagazinecargo ["ACE_Knicklicht_Y",5];	
	
	_box addmagazinecargo ["ACE_Bandage",50];
	_box addmagazinecargo ["ACE_LargeBandage",50];
	_box addmagazinecargo ["ACE_Morphine",50];
	_box addmagazinecargo ["ACE_Epinephrine",50];
	_box addmagazinecargo ["ACE_Medkit",50];
	
if (_class in _dm) then {
	_box addweaponcargo ["ACE_HK417_leupold",1];
	_box addweaponcargo ["SCAR_H_LNG_Sniper",1];
	_box addweaponcargo ["SCAR_H_LNG_Sniper_SD",1];
	_box addweaponcargo ["ACE_M14_ACOG",1];
	_box addweaponcargo ["M24_des_EP1",1];
	_box addweaponcargo ["DMR",1];
	_box addweaponcargo ["ACE_M110",1];
	_box addweaponcargo ["ACE_M110_SD",1];
	_box addweaponcargo ["M110_NVG_EP1",1];
	_box addweaponcargo ["M107",1];
	_box addweaponcargo ["M4SPR",1];
	_box addweaponcargo ["ACE_M4SPR_SD",1];	
};
	
if (_class in _ar) then {
	_box addweaponcargo ["ACE_M27_IAR",1];
	_box addweaponcargo ["ACE_M27_IAR_ACOG",1];
	_box addweaponcargo ["ACE_M27_IAR_CCO",1];
	_box addweaponcargo ["M249",1];
	_box addweaponcargo ["BAF_L110A1_Aim",1];
	_box addweaponcargo ["ACE_M249_AIM",1];
	_box addweaponcargo ["M249_EP1",1];
	_box addweaponcargo ["M249_m145_EP1",1];
	_box addweaponcargo ["ACE_M249_PIP_ACOG",1];	
};

if (_class in _mg) then {
	_box addweaponcargo ["M60A4_EP1",1];
	_box addweaponcargo ["Mk_48_DES_EP1",1];
	_box addweaponcargo ["ACE_M240B",1];
	_box addweaponcargo ["M240",1];
	_box addweaponcargo ["m240_scoped_EP1",1];
	_box addweaponcargo ["ACE_M240L",1];
	_box addweaponcargo ["ACE_M240L_M145",1];		
};

if (_class in _smaw) then {
	_box addweaponcargo ["SMAW",1];
};

if (_class in _tl) then {
	_box addweaponcargo ["ACE_MX2A",1];
	_box addweaponcargo ["Laserdesignator",1];
	_box addweaponcargo ["ACE_HuntIR_monitor",1];
	_box addmagazinecargo ["ACE_HuntIR_M203",10];
};

if (_class in _gl) then {
	_box addweaponcargo ["M16A2GL",1];
	_box addweaponcargo ["ACE_m16a2gl_scope",1];
	_box addweaponcargo ["M16A4_GL",1];
	_box addweaponcargo ["M16A4_ACG_GL",1];
	_box addweaponcargo ["ACE_M4_GL",1];
	_box addweaponcargo ["ACE_M4_AIM_GL",1];
	_box addweaponcargo ["ACE_M4_RCO_GL",1];
	_box addweaponcargo ["M4A1_HWS_GL",1];
	_box addweaponcargo ["M4A1_HWS_GL_SD_Camo",1];
	_box addweaponcargo ["M4A1_RCO_GL",1];
	_box addweaponcargo ["M4A3_RCO_GL_EP1",1];
	_box addweaponcargo ["ACE_M4A1_AIM_GL",1];
	_box addweaponcargo ["ACE_M4A1_AIM_GL_SD",1];
	_box addweaponcargo ["ACE_SOC_M4A1_GL",1];
	_box addweaponcargo ["ACE_SOC_M4A1_GL_SD",1];
	_box addweaponcargo ["ACE_SOC_M4A1_GL_13",1];
	_box addweaponcargo ["ACE_SOC_M4A1_GL_EOTECH",1];
	_box addweaponcargo ["ACE_SOC_M4A1_RCO_GL",1];
	_box addweaponcargo ["ACE_SOC_M4A1_GL_AIMPOINT",1];
	_box addweaponcargo ["ACE_HK416_D10_M320",1];
	_box addweaponcargo ["ACE_HK416_D14_COMPM3_M320",1];
	_box addweaponcargo ["SCAR_L_CQC_EGLM_Holo",1];
	_box addweaponcargo ["SCAR_L_STD_EGLM_RCO",1];
	_box addweaponcargo ["SCAR_H_STD_EGLM_Spect",1];
	_box addweaponcargo ["M8_carbineGL",1];	
	_box addweaponcargo ["Mk13_EP1",1];
	_box addweaponcargo ["M79_EP1",1];
};	

sleep 1800;

};